#!/bin/sh
# Gaohe: Replacement of Debian wrapper script for pymol
# debian wrapper script for pymol

test -r ${HOME}/.pymol && . ${HOME}/.pymol

# Distribution from ap will have a conflict with conda 
PYMOL_PATH=${PYMOL_PATH:=`/usr/bin/python3 -c "from imp import find_module; print(find_module('pymol')[1])"`}
PYMOL_DATA=${PYMOL_DATA:=/usr/share/pymol/data}
PYMOL_SCRIPTS=${PYMOL_SCRIPTS:=/usr/share/pymol/scripts}
CHEMPY_DATA=${CHEMPY_DATA:=/usr/share/pymol/data/chempy}

export PYMOL_PATH
export PYMOL_DATA
export PYMOL_SCRIPTS
export CHEMPY_DATA

/usr/bin/python3 -m pymol.__init__ ${1+"$@"}
